"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EMAIL_TEMPLATE_PATH = exports.LIMIT = exports.PORT_DEV = exports.MAILTRAP_PASS = exports.MAILTRAP_USER = exports.MAILTRAP_PORT = exports.MAILTRAP_HOST = exports.NODE_ENV = exports.CLIENT_URL = exports.BCRYPT_SALT = exports.EMAIL_PORT = exports.FROM_EMAIL = exports.EMAIL_PASSWORD = exports.EMAIL_USERNAME = exports.EMAIL_HOST = exports.JWT_SECRET = exports.MONGO_URI = void 0;
const tslib_1 = require("tslib");
const path_1 = tslib_1.__importDefault(require("path"));
exports.MONGO_URI = "mongodb+srv://rickyandrianaivo:2tkMQr6UkB4vexKT@ids.ll4k7bh.mongodb.net/etokisana";
exports.JWT_SECRET = 'e-tokisana';
exports.EMAIL_HOST = 'commercegestion.com';
exports.EMAIL_USERNAME = 'contact@commercegestion.com';
exports.EMAIL_PASSWORD = 'Rzh398aNVtFZUu4';
exports.FROM_EMAIL = 'contact@commercegestion.com';
exports.EMAIL_PORT = 465;
exports.BCRYPT_SALT = 10;
exports.CLIENT_URL = 'https://www.commercegestion.com';
exports.NODE_ENV = 'DEV';
exports.MAILTRAP_HOST = 'sandbox.smtp.mailtrap.io';
exports.MAILTRAP_PORT = 2525;
exports.MAILTRAP_USER = '2a6a049ea742dd';
exports.MAILTRAP_PASS = '1b8d17f7b2651a';
exports.PORT_DEV = 3000;
exports.LIMIT = '50mb';
exports.EMAIL_TEMPLATE_PATH = path_1.default.join(__dirname, '../../Utils/Emails/Template');
//# sourceMappingURL=constant.js.map